/* 2251265 ¼Æ°Î ËÕ´«Öİ */
void popstar(char input);
void print_popstar(int x, int y, int array[][10], int array1[][10], int choice);
void creat_array(int x, int y, int array[][10]);
void input_x_y(int& x, int& y);
void popstar_1(int& x, int& y, int array[][10], int array1[][10], char& hang, int& lie);
int popstar_2(int& x, int& y, int array[][10], int array1[][10], char hang, int lie, int& score_total);
void popstar_3(int& x, int& y, int array[][10], int array1[][10], char& hang, int& lie, int& score_total);
void popstar_4(int x, int y, int array[][10]);
void popstar_5(int x, int y, int array[][10]);
void popstar_6(int x, int y, int array[][10]);
int popstar_7(int x, int y, int array[][10], int& score_total);
void input_location(int& lie, char& hang, int x, int y);
void check_around(int x, int y, char hang, int lie, int  array[][10], int  array1[][10]);
int check_star(int x, int y, int array1[][10]);
void check_end();
int tj_strcasencmp(const char* s1, const char* s2, const int len);
void downput_and_rightput(int x, int y, int array[][10]);
int check_left(int x, int y, int array[][10]);
int gift(int x, int y, int array[][10]);
void print_border(int x, int y, int array[][10]);
void print_border_pro(int x, int y, int array[][10]);
void print_star(int x, int y, int array[][10]);
void print_star_pro(int x, int  y, int  array[][10]);
void read_mouse_and_key(int x, int y, int array[][10], int input);
int read_mouse_and_key_pro(int x, int y, int array[][10], int input, int& score_total);
void change_color(int x1, int y1, int array[][10], int x);
void change_color_pro(int x1, int y1, int array[][10], int x);
void drop(int x, int y, int array[][10], int input);
int distroy(int x, int y, int array[][10], int& x1, int& y1);
int distroy_pro(int x, int y, int array[][10], int& x1, int& y1, int& score);
void key_move(int x, int y, int& x1, int& y1, int array[][10], int array1[][10], int key2, int input);
void key_result(int x, int y, int& x1, int& y1, int key2, int array[][10]);
void mouse_move(int x, int y, int& x1, int& y1, int array[][10], int my, int mx, int input);
void huiche();
